"""
Pydantic v2 schema for newsletter data generated by Claude.
Validates and coerces data before processing (save/send).
"""

from typing import Literal

from pydantic import BaseModel, field_validator, model_validator


class ArticleSource(BaseModel):
    title: str
    url: str
    source: str


class Article(BaseModel):
    rank: int
    title: str
    flash: str
    detail: str
    topic: str
    hype: Literal["viral", "trending", "notable"]
    sources: list[ArticleSource]

    @field_validator("sources")
    @classmethod
    def at_least_one_source(cls, v: list) -> list:
        if not v:
            raise ValueError("sources must contain at least one entry")
        return v


class NewsletterData(BaseModel):
    subject: str
    newsletter_title: str
    intro: str
    articles: list[Article]
    conclusion: str

    @field_validator("articles", mode="before")
    @classmethod
    def parse_articles_string(cls, v):
        """Absorb Claude occasionally sending articles as a JSON string."""
        if isinstance(v, str):
            import json
            try:
                v = json.loads(v)
            except Exception as exc:
                raise ValueError(f"articles is a non-parsable JSON string: {exc}") from exc
        return v

    @field_validator("articles")
    @classmethod
    def articles_not_empty(cls, v: list) -> list:
        if not v:
            raise ValueError("articles must contain at least one article")
        return v
